package us.john.hanna.cps530assignment.entities;

import lombok.Data;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

// MappedSuperclass signifies this will be a superclass for our entities
@MappedSuperclass
/*
 Data is a lombok annotation to implicitly generate toString, hashCode, equals, getters, setters, and a constructor
 to set the fields in this class!
 */
@Data
public class BaseEntity {
    // @Id specifies that this field will be the id for any entity inheriting this
    @Id
    // @GeneratedValue specifies that this id will be autogenerated by hibernate
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

}
